import json
import tomllib

from bron.gen_codex import generate
from bron.loader import load
from bron.prompts import agent_prompt
from vaultkit import add_agent, add_connection, set_meta

BRON = ("System", "Agents", "Bron", "Agent.md")


def config(vault):
    raw = generate(load(vault))[".codex/config.toml"].decode()
    assert raw.startswith("# Generated by Bron")
    return tomllib.loads(raw)


def test_config_carries_bron_instructions_and_memory_off(vault):
    cfg = config(vault)
    assert cfg["developer_instructions"].startswith("# You are Bron\n")
    assert "model" not in cfg
    assert cfg["features"]["memories"] is False
    assert "mcp_servers" not in cfg


def test_pinned_codex_model(vault):
    set_meta(vault.root.joinpath(*BRON), models={"claude": "default", "codex": "gpt-6.1-sol"})
    assert config(vault)["model"] == "gpt-6.1-sol"


def test_servers_are_disabled_unless_allowed_and_tools_get_approvals(vault):
    add_connection(vault, "Gmail")
    add_connection(vault, "Carta", env={"CARTA_TOKEN": "${CARTA_TOKEN}", "REGION": "us"})
    set_meta(vault.root.joinpath(*BRON), connections=["Gmail"], ask_before=["send-email"], always_allow=["mcp:gmail:reply_to_message"])
    servers = config(vault)["mcp_servers"]
    gmail = servers["gmail"]
    assert "enabled" not in gmail
    assert gmail["command"] == "uvx" and gmail["args"] == ["mcp-server-time"]
    assert gmail["tools"]["send_message"]["approval_mode"] == "prompt"
    assert gmail["tools"]["reply_to_message"]["approval_mode"] == "approve"
    carta = servers["carta"]
    assert carta["enabled"] is False
    assert carta["env"] == {"REGION": "us"}
    assert carta["env_vars"] == ["CARTA_TOKEN"]


def test_http_server(vault):
    add_connection(vault, "Docs", type="mcp-http", url="https://docs.example/mcp", command="")
    set_meta(vault.root.joinpath(*BRON), connections=["Docs"])
    assert config(vault)["mcp_servers"]["docs"] == {"url": "https://docs.example/mcp"}


def test_shell_rules_file(vault):
    rules = generate(load(vault))[".codex/rules/bron.rules"].decode()
    assert rules.startswith("# Generated by Bron")
    assert 'prefix_rule(pattern=["git", "push"], decision="prompt")' in rules
    assert 'prefix_rule(pattern=["rm"], decision="prompt")' in rules


def test_no_rules_file_without_shell_rules(vault):
    set_meta(vault.root.joinpath(*BRON), ask_before=[])
    assert ".codex/rules/bron.rules" not in generate(load(vault))


def test_hooks_json_has_the_fixed_triggers(vault):
    hooks = json.loads(generate(load(vault))[".codex/hooks.json"])["hooks"]
    assert hooks["SessionStart"][0]["hooks"][0]["command"].endswith("hook session-start --cli codex")
    assert hooks["SessionEnd"][0]["hooks"][0]["timeout"] <= 3


def test_helpers_become_codex_agents_but_team_members_do_not(vault):
    add_agent(vault, "CFO")
    add_connection(vault, "Carta")
    files = generate(load(vault))
    assert ".codex/agents/reader.toml" in files
    assert ".codex/agents/cfo.toml" not in files and ".codex/agents/bron.toml" not in files
    reader = tomllib.loads(files[".codex/agents/reader.toml"].decode())
    assert reader["name"] == "reader"
    assert reader["sandbox_mode"] == "read-only"
    assert reader["developer_instructions"].startswith("# You are the reader helper")
    assert "mcp_servers" not in reader  # Codex rejects or ignores per-agent server tables (verification R4)


def test_skills_go_to_the_agents_folder(vault):
    assert ".agents/skills/check/SKILL.md" in generate(load(vault))


def test_tricky_instructions_survive_toml(vault):
    path = vault.root.joinpath(*BRON)
    path.write_text(path.read_text() + '\nQuote: """triple""" and \\backslash and "quotes" and ção.\n', encoding="utf-8")
    loaded = load(vault)
    assert config(vault)["developer_instructions"] == agent_prompt(loaded.agents["bron"], loaded)
