"""Codex's view of the vault: .codex/ and .agents/skills/ (AGENTS.md is shared, see agents_md.py).

Team members are deliberately not written as .codex/agents files, so Codex can't spawn them as
subagents; the runner and launcher start them with flags instead.
"""
from __future__ import annotations

import json

import tomli_w

from .access import allowed_keys
from .catalog import Actions
from .hookconfig import hooks_block
from .loader import Config
from .model import Helper
from .prompts import agent_prompt, helper_prompt
from .skills import skill_files

HEADER = "# Generated by Bron from System/. Do not edit: change System/ or ask Bron.\n"


def team_permissions(cfg: Config) -> tuple[Actions, Actions]:
    """(ask, allow) for the vault's Codex setup, which every Codex session in the vault shares.

    Any agent's ask applies; an allow only when every agent allows it.
    """
    ask, allow = Actions(), None
    for _, agent in sorted(cfg.agents.items()):
        own_ask, own_allow = cfg.catalog.permissions_for(agent)
        for conn, tools in own_ask.mcp.items():
            ask.mcp.setdefault(conn, set()).update(tools)
        for words in own_ask.shell:
            ask.add_shell(words)
        if allow is None:
            allow = own_allow
            continue
        allow.mcp = {conn: tools & own_allow.mcp.get(conn, set()) for conn, tools in allow.mcp.items()}
        allow.mcp = {conn: tools for conn, tools in allow.mcp.items() if tools}
        allow.shell = [words for words in allow.shell if words in own_allow.shell]
    return ask, allow if allow is not None else Actions()


def generate(cfg: Config) -> dict[str, bytes]:
    ask, allow = team_permissions(cfg)
    files = {
        ".codex/config.toml": _toml(_config(cfg, ask, allow)),
        ".codex/hooks.json": (json.dumps({"hooks": hooks_block(cfg.vault, "codex")}, indent=2) + "\n").encode("utf-8"),
    }
    rules = _rules(ask, allow)
    if rules:
        files[".codex/rules/bron.rules"] = rules.encode("utf-8")
    for key, helper in sorted(cfg.helpers.items()):
        files[f".codex/agents/{key}.toml"] = _toml(_helper(cfg, helper))
    files.update(skill_files(cfg, ".agents/skills"))
    return files


def _config(cfg: Config, ask: Actions, allow: Actions) -> dict:
    agent = cfg.default_agent
    doc: dict = {}
    model = cfg.catalog.resolve_model("codex", agent.models.get("codex"))
    if model:
        doc["model"] = model
    doc["developer_instructions"] = agent_prompt(agent, cfg)
    doc["features"] = {"memories": False}
    servers = _servers(cfg, agent.connections, ask, allow)
    if servers:
        doc["mcp_servers"] = servers
    return doc


def _servers(cfg: Config, allowed: list[str], ask: Actions, allow: Actions) -> dict:
    keep = allowed_keys(cfg, allowed)
    out: dict = {}
    for key, conn in sorted(cfg.connections.items()):
        if conn.type == "native":
            continue  # defined in the user's own Codex config; per-agent limits are applied at launch
        if conn.type == "mcp-http":
            server: dict = {"url": conn.url}
        else:
            server = {"command": conn.command, "args": list(conn.args)}
        literal = {k: v for k, v in conn.env.items() if v != f"${{{k}}}"}
        passthrough = sorted(k for k, v in conn.env.items() if v == f"${{{k}}}")
        if literal:
            server["env"] = literal
        if passthrough:
            server["env_vars"] = passthrough
        if key not in keep:
            server["enabled"] = False
        tools = {tool: {"approval_mode": "prompt"} for tool in sorted(ask.mcp.get(key, ()))}
        tools.update({tool: {"approval_mode": "approve"} for tool in sorted(allow.mcp.get(key, ()))})
        if tools:
            server["tools"] = tools
        out[key] = server
    return out


def _rules(ask: Actions, allow: Actions) -> str:
    lines = [f'prefix_rule(pattern={json.dumps(list(words), ensure_ascii=False)}, decision="prompt")' for words in ask.shell]
    lines += [f'prefix_rule(pattern={json.dumps(list(words), ensure_ascii=False)}, decision="allow")' for words in allow.shell]
    return HEADER + "\n".join(lines) + "\n" if lines else ""


def _helper(cfg: Config, helper: Helper) -> dict:
    doc: dict = {"name": helper.key, "description": helper.description, "developer_instructions": helper_prompt(helper)}
    model = cfg.catalog.resolve_model("codex", helper.models.get("codex"))
    if model:
        doc["model"] = model
    if helper.read_only:
        doc["sandbox_mode"] = "read-only"
    # No [mcp_servers] tables: Codex rejects one without a transport and does not hide a server
    # listed with enabled = false (verification R4). Per-helper connection limits are a Plan 2 item.
    return doc


def _toml(doc: dict) -> bytes:
    return (HEADER + tomli_w.dumps(doc, multiline_strings=True)).encode("utf-8")
